# Generated by Django 3.0.7 on 2020-06-08 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('name', models.CharField(max_length=64)),
                ('customer_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('refresh_token', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('GBP', 'GBP'), ('EUR', 'EUR')], max_length=64)),
                ('accountUid', models.CharField(max_length=64)),
                ('accountholder', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='piggybank.Customer')),
            ],
        ),
    ]
